apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: {{ .Values.Name  }}
   namespace: {{ .Values.namespace }}
   labels:
     service: {{ .Values.service.name }}
     env: {{ .Values.env }}
spec:
   serviceName: {{ .Values.service.name }}
   replicas:  {{ .Values.replicaCount }}
   updateStrategy:
      type: RollingUpdate
   selector:
      matchLabels:
         service: {{ .Values.service.name }}
         env:  {{ .Values.env}}
   template:
      metadata:
         labels:
           service: {{ .Values.service.name }}
           env: {{ .Values.env }}
      spec:
         terminationGracePeriodSeconds: 40
        {{- with .Values.securityContext }}
         securityContext:
           {{- toYaml . | nindent 11 }}
         {{- end }}
         {{- if .Values.image.usePullSecret }}
         imagePullSecrets:
            - name: {{ .Values.image.pullSecretName }}
         {{- end }}
         containers:
            - name: {{ .Values.containers.name | default "nifi" }}
              image: "{{ .Values.image.registry }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              ports:
                {{- range .Values.containers.ports }}
                 - name: {{ .name }}
                   containerPort: {{ .containerPort}}
                {{- end }}
              {{- if .Values.envvar.enabled }}
              env:
              {{- if .Values.envvar.envkeyval.enabled }}
              {{- range .Values.envvar.envkeyval.list }}
                - name: {{ quote .name }}
                  value: {{ quote .value }}
              {{- end }}
              {{- end}}
              {{- end }}
              {{- with .Values.probes.livenessProbe }}
              livenessProbe:
                 {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.probes.readinessProbe }}
              readinessProbe:
                 {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.resources }}
              resources:
                 {{- toYaml . | nindent 15 }}
              {{- end }}
              {{- if .Values.volumemounts.enabled }}
              volumeMounts:
                {{- range .Values.volumemounts.mount }}
                 - name: {{ .name }}
                   mountPath: {{ .mountPath }}
                {{- end}}
              {{- end }}
   {{- if .Values.volumeClaimTemplates.enabled }}
   volumeClaimTemplates:
     {{- range .Values.volumeClaimTemplates.claim }}
    - metadata:
        name: {{ .name }}
      spec:
        accessModes:
          -  {{  .accessModes }}
        resources:
          requests:
            storage: {{ .size }}
        storageClassName: {{ .storageClass }}
    {{- end }}
{{- end }}
