apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace}}
  {{- if .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadbalancerInternal_IP }}
  {{- with .Values.service.annotations }}
  annotations:
     {{- toYaml . | nindent 5 }}
   {{- end}}
   {{- end}}
   {{- end}}
   {{- end}}
  labels:
     service: {{ .Values.service.name }}
     env: {{ .Values.env}}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort}}
    {{- end }}
  selector:
     service: {{ .Values.service.name }}
     env: {{ .Values.env}}
  {{- if .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.staticIP }}
  loadBalancerIP: {{ .Values.service.staticLoadBalancerIp }}
  {{- end}}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
     {{- toYaml . | nindent 5 }}
   {{- end}}
   {{- end }}
   {{- end }}
